### ISSUE TITLE
What are you building??? :)

### ISSUE THREAD

**Issue by chrism2671** [mrded/temp-unit#1]

**Comment by mrded** [comment]
haha, it's a swarm of small temperature and humidity sensors on ESP8266 and DHT11.

Looks like this:

![94e9aa43e01dab39](https://user-images.githubusercontent.com/347098/83553224-cf9e5800-a502-11ea-8d09-b187b2867581.jpg)

I got a kilo of those, they are really cheap. 

It sends temperature and humidity readings over HTTP, so I can collect it and show on a dashboard.

![Screenshot 2020-06-02 at 18 58 58](https://user-images.githubusercontent.com/347098/83553478-2a37b400-a503-11ea-8d5a-b22a5354f86d.png)

I should probably make a readme :)

**Comment by mrded** [comment]
Read about [ESP8266](https://tttapa.github.io/ESP8266/Chap01%20-%20ESP8266.html), this little thing is awesome.

**Comment by chrism2671** [comment]
Wow this is awesome!!! :)

**Comment by mrded** [comment]
Pictures for using in readme:
![esp_programmer](https://user-images.githubusercontent.com/347098/83556336-99afa280-a507-11ea-8cce-bc25e2ddb423.jpg)

![original](https://user-images.githubusercontent.com/347098/83556426-c663ba00-a507-11ea-9a6f-1abed942dff8.jpg)

![Screenshot 2020-06-02 at 19 33 17](https://user-images.githubusercontent.com/347098/83556502-ef844a80-a507-11ea-8f1c-3e142b1d71a6.png)

![e2a5fd98-9d39-4b97-a9a0-f875f4289916](https://user-images.githubusercontent.com/347098/83557074-e9429e00-a508-11ea-91c2-62bfef342909.jpg)

**Comment by mrded** [comment]
I made a readme https://github.com/mrded/temp-unit/blob/master/README.md
